// EAS Update fingerprint (runtimeVersion) tooling.
//
//   node scripts/fingerprint.mjs                 # print current per-platform hashes
//   node scripts/fingerprint.mjs check           # exit EXIT_DRIFT if drifted from baselines (CI)
//   node scripts/fingerprint.mjs update <build>  # set a baseline from a built artifact
//
// Exit codes: 0 = OK/no drift, EXIT_DRIFT = drift detected, anything else = the
// tool failed to run. Drift uses a DEDICATED code (not 1) so CI can tell real
// drift apart from a generic Node failure — an uncaught error (e.g. a missing
// module at import-time) also exits 1, and must not be reported as drift.
//
// The baselines in common/src/mobileFingerprints.ts represent the builds
// currently live in the stores. A drift (check) means the native layer changed,
// so the change CANNOT ship to existing installs over OTA — a new App Store /
// Play Store build is required. The server also serves the baselines to
// installed apps, which prompt for a store update when their own fingerprint no
// longer matches — so run `update` once the build is LIVE in the store (not at
// submission), and let the commit deploy promptly after.
//
// Each baseline also records the store build's app version (semver). Installed
// apps use it to order themselves against the store build: fingerprints are
// unordered hashes, so a mismatch alone can't distinguish "this install is
// behind the store" from "the server's baseline hasn't caught up to this build
// yet". Apps only prompt when the baseline version is strictly NEWER than
// their own — which means every store build MUST bump `version` in
// app.config.js, or its predecessor's users are never prompted.
//
// `update` reads the fingerprint baked INTO the artifact you submitted (rather
// than recomputing from the working tree), so the baseline reflects exactly
// what shipped — no "trust me, I built it from this commit". The hash lives at:
//   iOS:     <.ipa|.app|.xcarchive>  ->  EXUpdates.bundle/fingerprint
//   Android: <.aab|.apk>             ->  assets/fingerprint
// (Both .ipa and .aab/.apk are plain zips; .app/.xcarchive are directories.)
//
// `check`/print recompute the fingerprint, so run those with APP_VARIANT=production
// (the package.json scripts set it); `update` reads a file and needs no variant.

import { createFingerprintAsync } from "@expo/fingerprint";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PROJECT_ROOT = path.join(import.meta.dirname, "..");
const PLATFORMS = ["ios", "android"];
const FINGERPRINT_RE = /^[0-9a-f]{40}$/;
const SEMVER_RE = /^\d+\.\d+\.\d+$/;
// Dedicated drift exit code, deliberately not 1 (Node's generic uncaught-error
// code) nor 2 (used by die() and the top-level catch below for tool failures).
const EXIT_DRIFT = 3;

async function currentHash(platform) {
  const { hash } = await createFingerprintAsync(PROJECT_ROOT, {
    platforms: [platform],
  });
  return hash;
}

// The baselines live in common/ (not in this package) because the server
// serves them to installed apps at runtime, so a stale install can prompt for
// a store update.
const FINGERPRINTS_FILE = path.join(
  PROJECT_ROOT,
  "..",
  "..",
  "common",
  "src",
  "mobileFingerprints.ts",
);

function fingerprintsFileContents(baselines) {
  const entries = PLATFORMS.map((platform) => {
    const { fingerprint = "", version = "" } = baselines[platform] ?? {};
    return [
      `  ${platform}: {`,
      `    fingerprint: "${fingerprint}",`,
      `    version: "${version}",`,
      `  },`,
    ].join("\n");
  }).join("\n");
  return `// Generated by \`bun run fingerprint:update\` in apps/mobile — do not edit by
// hand. The EAS Update runtime fingerprints and app versions of the mobile
// builds currently live in the stores. The server exposes these so installed
// apps can detect that a newer store build exists: their own
// Updates.runtimeVersion no longer matches, and \`version\` is newer than
// their own — fingerprints alone are unordered, so the semver breaks the tie
// when the server's baseline lags the store (deploy window after a release).
export const MOBILE_STORE_FINGERPRINTS = {
${entries}
} as const;
`;
}

// Parses rather than imports FINGERPRINTS_FILE (this script runs under plain
// node, which can't load TS). The file is machine-written, so anything that
// doesn't match the generated shape means it was edited by hand.
function readBaselines() {
  if (!fs.existsSync(FINGERPRINTS_FILE)) {
    return Object.fromEntries(PLATFORMS.map((platform) => [platform, null]));
  }
  const source = fs.readFileSync(FINGERPRINTS_FILE, "utf8");
  const baselines = {};
  for (const platform of PLATFORMS) {
    const match = source.match(
      new RegExp(
        `^  ${platform}: \\{\n` +
          `    fingerprint: "([0-9a-f]{40}|)",\n` +
          `    version: "(\\d+\\.\\d+\\.\\d+|)",\n` +
          `  \\},$`,
        "m",
      ),
    );
    if (!match) {
      die(
        `common/src/mobileFingerprints.ts has no parseable "${platform}" entry — it is generated, so restore it from git instead of editing by hand`,
      );
    }
    baselines[platform] = match[1]
      ? { fingerprint: match[1], version: match[2] }
      : null;
  }
  return baselines;
}

// The app version that will ship alongside the fingerprint baseline. Read
// (textually — this script runs under plain node, which can't import the
// Expo-transpiled config) from app.config.js rather than extracted from the
// artifact: pulling the version out of an .ipa/.aab needs plutil/bundletool,
// which is more machinery than the weaker provenance is worth. `update` is
// run from the release commit, where the two match; the output echoes the
// version so the operator can eyeball it against the store listing.
function readAppVersion() {
  const configPath = path.join(PROJECT_ROOT, "app.config.js");
  const source = fs.readFileSync(configPath, "utf8");
  const match = source.match(/^\s*version: "([^"]+)",$/m);
  if (!match || !SEMVER_RE.test(match[1])) {
    die(
      `could not read a semver \`version: "x.y.z",\` line from app.config.js`,
    );
  }
  return match[1];
}

function isNewerVersion(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const ai = pa[i] ?? 0;
    const bi = pb[i] ?? 0;
    if (ai > bi) return true;
    if (ai < bi) return false;
  }
  return false;
}

function ensureVersionBumpedForNewFingerprint(
  platform,
  baseline,
  hash,
  version,
) {
  if (!baseline?.fingerprint || baseline.fingerprint === hash) {
    return;
  }
  if (!baseline.version) {
    die(
      `existing ${platform} baseline has no version; restore common/src/mobileFingerprints.ts from git and rerun update`,
    );
  }
  if (isNewerVersion(version, baseline.version)) {
    return;
  }
  die(
    `${platform} fingerprint changed but app.config.js version stayed at ${version}; bump it above the current store baseline (${baseline.version}) before running fingerprint:update`,
  );
}

function die(message) {
  console.error(`Error: ${message}`);
  // Exit 2 ("tool failed to run"), matching the top-level catch — kept distinct
  // from EXIT_DRIFT (3) and Node's generic uncaught-error code (1).
  process.exit(2);
}

// --- artifact extraction (the `update` command) ---

function readZipEntry(zipPath, endsWith, label) {
  const entries = execFileSync("unzip", ["-Z1", zipPath], { encoding: "utf8" })
    .split("\n")
    .filter(Boolean);
  const entry = entries.find((e) => e.endsWith(endsWith));
  if (!entry) {
    die(
      `no embedded ${label} fingerprint (${endsWith}) inside ${path.basename(zipPath)}`,
    );
  }
  return execFileSync("unzip", ["-p", zipPath, entry], {
    encoding: "utf8",
  }).trim();
}

function readDirEntry(dir, suffix, label) {
  const stack = [dir];
  while (stack.length) {
    const current = stack.pop();
    for (const e of fs.readdirSync(current, { withFileTypes: true })) {
      const p = path.join(current, e.name);
      if (e.isDirectory()) stack.push(p);
      else if (p.endsWith(suffix)) return fs.readFileSync(p, "utf8").trim();
    }
  }
  die(`no ${label} fingerprint (${suffix}) found under ${dir}`);
}

function extractFromArtifact(artifact) {
  if (!artifact) {
    die(
      "usage: node scripts/fingerprint.mjs update <path-to-.ipa|.app|.xcarchive|.aab|.apk>",
    );
  }
  if (!fs.existsSync(artifact)) die(`no such artifact: ${artifact}`);

  const ext = path.extname(artifact).toLowerCase();
  const IOS_SUFFIX = path.join("EXUpdates.bundle", "fingerprint");

  switch (ext) {
    case ".ipa":
      return {
        platform: "ios",
        hash: readZipEntry(artifact, "EXUpdates.bundle/fingerprint", "iOS"),
      };
    case ".app":
    case ".xcarchive":
      return {
        platform: "ios",
        hash: readDirEntry(artifact, IOS_SUFFIX, "iOS"),
      };
    case ".aab":
    case ".apk":
      return {
        platform: "android",
        hash: readZipEntry(artifact, "assets/fingerprint", "Android"),
      };
    default:
      die(
        `unsupported artifact type "${ext}" — expected .ipa/.app/.xcarchive/.aab/.apk`,
      );
  }
}

// --- commands ---

async function run() {
  const command = process.argv[2] ?? "print";

  if (command === "update") {
    const { platform, hash } = extractFromArtifact(process.argv[3]);
    if (!FINGERPRINT_RE.test(hash)) {
      die(`extracted value is not a fingerprint: "${hash}"`);
    }
    const version = readAppVersion();
    const baselines = readBaselines();
    ensureVersionBumpedForNewFingerprint(
      platform,
      baselines[platform],
      hash,
      version,
    );
    baselines[platform] = { fingerprint: hash, version };
    fs.writeFileSync(FINGERPRINTS_FILE, fingerprintsFileContents(baselines));
    console.log(`${platform}: ${hash} (version ${version})`);
    console.log(
      "wrote common/src/mobileFingerprints.ts — version was read from app.config.js; confirm it matches the build now live in the store",
    );
    return;
  }

  if (command === "check") {
    const baselines = readBaselines();
    const drifted = [];
    for (const platform of PLATFORMS) {
      const current = await currentHash(platform);
      const baseline = baselines[platform]?.fingerprint ?? null;
      if (current !== baseline) drifted.push({ platform, baseline, current });
    }

    if (drifted.length === 0) {
      console.log("Mobile fingerprint unchanged — changes are OTA-shippable.");
      return;
    }

    console.log("FINGERPRINT_DRIFT");
    for (const { platform, baseline, current } of drifted) {
      console.log(`${platform}: ${baseline ?? "(no baseline)"} -> ${current}`);
    }
    process.exitCode = EXIT_DRIFT;
    return;
  }

  for (const platform of PLATFORMS) {
    console.log(`${platform}: ${await currentHash(platform)}`);
  }
}

run().catch((error) => {
  console.error(error);
  process.exitCode = 2;
});
