// Generated by `bun run fingerprint:update` in apps/mobile — do not edit by
// hand. The EAS Update runtime fingerprints and app versions of the mobile
// builds currently live in the stores. The server exposes these so installed
// apps can detect that a newer store build exists: their own
// Updates.runtimeVersion no longer matches, and `version` is newer than
// their own — fingerprints alone are unordered, so the semver breaks the tie
// when the server's baseline lags the store (deploy window after a release).
export const MOBILE_STORE_FINGERPRINTS = {
  ios: {
    fingerprint: "10ae0b1b177a351ff60e550ff1512a6b255bbabd",
    version: "1.2.1",
  },
  android: {
    fingerprint: "601dfc7b787a9d6b30a93f73ec86693db49cb374",
    version: "1.2.1",
  },
} as const;
