name: Test Backend Unit

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string

jobs:
  test-backend-unit:
    environment: ${{ inputs.environment || '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Backend Dependencies
        run: bun install --frozen-lockfile
        working-directory: ./server

      - name: Install @alliance/common dependencies
        run: bun install --frozen-lockfile
        working-directory: ./common

      - name: Typecheck
        run: bun typecheck
        working-directory: ./server

      - name: Run Unit Tests
        run: bun test
        working-directory: ./server
